# fly.toml app configuration file generated for searchface on 2025-06-29T11:18:15+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'searchface'
primary_region = 'nrt'

[build]
  strategy = "rolling"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = 512
  size = 'shared-cpu-1x'

[scale]
  count = 1